# 
# File: Makefile
#
# Contents: This file is to "make" the CVS related scripts
#
# This file is a makefile template.
#

exports = ci-comp comp.dir get get-comp get-script maint-rel new-comp prod-rel \
	put put-comp put-script tag-all test-rel

srcs = 

targ = 

include $(mk)/scripts.mk

